apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-master-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: popo

