apiVersion: v1
kind: Service
metadata:
  labels:
    app: locust-master
  name: locust-master
spec:
  ports:
  - name: master-web
    nodePort: 30060
    port: 8089
    targetPort: master-web
  - name: master-p1
    nodePort: 30061
    port: 5557
    targetPort: master-p1
  - name: master-p2
    nodePort: 30062
    port: 5558
    targetPort: master-p2
  selector:
    app: locust-master
  type: NodePort
